
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Tue Oct 15 11:34:53 CDT 2024
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int MINUS_MINUS = 62;
  static final int SHORT = 49;
  static final int SIGNED = 52;
  static final int TIMES = 17;
  static final int GT = 6;
  static final int EQUAL_EQUAL = 83;
  static final int CONST = 47;
  static final int INT_LITERAL = 4;
  static final int PLUS_EQUAL = 75;
  static final int AND_EQUAL = 79;
  static final int GE = 13;
  static final int DOUBLE_RIGHT_ARROW = 66;
  static final int REGISTER = 41;
  static final int ENUM = 40;
  static final int SIZEOF = 56;
  static final int COMMA = 18;
  static final int RBRACE = 34;
  static final int RPAREN = 23;
  static final int LT = 14;
  static final int AND_AND = 69;
  static final int BACKSPACE = 84;
  static final int STRUCT = 37;
  static final int LBRACE = 33;
  static final int LPAREN = 22;
  static final int POUND = 60;
  static final int LE = 19;
  static final int NIL = 11;
  static final int STAR_EQUAL = 72;
  static final int TILDA = 63;
  static final int VAR = 29;
  static final int FLOAT = 48;
  static final int GOTO = 55;
  static final int PLUS_PLUS = 61;
  static final int EQ = 35;
  static final int DOUBLE_LEFT_ARROW = 65;
  static final int PLUS = 32;
  static final int PERCENT = 64;
  static final int DIVIDE = 7;
  static final int B_OR = 10;
  static final int WHILE = 26;
  static final int UNION = 46;
  static final int PERCENT_EQUAL = 74;
  static final int ASSIGN = 20;
  static final int CHAR = 43;
  static final int OR_EQUAL = 81;
  static final int SWITCH = 38;
  static final int DO = 12;
  static final int FOR = 16;
  static final int STAR = 59;
  static final int VOID = 53;
  static final int EXTERN = 44;
  static final int RETURN = 45;
  static final int CARROT = 68;
  static final int ELSE = 9;
  static final int BREAK = 30;
  static final int DOT = 21;
  static final int INT = 5;
  static final int SLASH_EQUAL = 73;
  static final int EOF = 0;
  static final int SEMICOLON = 25;
  static final int COMMENT = 85;
  static final int POUND_POUND = 82;
  static final int CARROT_EQUAL = 80;
  static final int DEFAULT = 54;
  static final int MINUS = 15;
  static final int OR = 70;
  static final int error = 1;
  static final int NOT_EQUAL = 67;
  static final int CONTINUE = 51;
  static final int MINUS_EQUAL = 76;
  static final int IF = 24;
  static final int UNSIGNED = 50;
  static final int ID = 2;
  static final int COLON = 8;
  static final int DOUBLE_RIGHT_ARROW_EQUAL = 78;
  static final int RBRACKET = 28;
  static final int VOLATILE = 57;
  static final int CASE = 39;
  static final int STRING = 3;
  static final int QUESTION_MARK = 71;
  static final int AND = 31;
  static final int STATIC = 58;
  static final int LBRACKET = 27;
  static final int TYPEDEF = 42;
  static final int DOUBLE_LEFT_ARROW_EQUAL = 77;
  static final int AUTO = 36;

  /* non terminals */
  static final int Exp = 1;
  static final int $START = 0;
  static final int Var = 2;
}

